In [1]:
import cv2
import numpy as np

In [6]:
img = cv2.imread("kartt.png")
cv2.imshow("original",img)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [9]:
width = 400
height = 500

pts1 = np.float32([[230,1],[1,472],[540,150],[338,617]])
pts2 = np.float32([[0,0],[0,height],[width,0],[width,height]])

matrix = cv2.getPerspectiveTransform(pts1,pts2)
print(matrix)

imgOutput = cv2.warpPerspective(img,matrix,(width,height))

cv2.imshow("original",img)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 9.88318421e-01  4.80519997e-01 -2.27793757e+02]
 [-4.28952606e-01  8.92451730e-01  9.77666476e+01]
 [-1.23898125e-04  7.89697479e-05  1.00000000e+00]]
